version: '3.3'

services:
  web:
    build: .
    restart: always
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres:14-alpine
    restart: always
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_PORT=${DATABASE_PORT}
    volumes:
      - taxation-data:/var/lib/postgresql/data
    env_file:
      - .env
volumes:
  taxation-data: